/**
 * MULTI-CHECK-ALLOCATION-DOMAIN-1 — pure Multi Check Allocation domain barrel.
 * ADR-ARCH-025 · Check-owned FSP capability · NOT an Aggregate Root · no persistence.
 */

export {
  MULTI_CHECK_ALLOCATION_PROGRAM_ID,
  MULTI_CHECK_ALLOCATION_ADR_ID,
  ALLOCATION_STATUSES,
  ALLOCATION_NON_TERMINAL_STATUSES,
  ALLOCATION_TERMINAL_STATUSES,
  ALLOCATION_SUCCESS_TERMINAL_STATUSES,
  isAllocationStatus,
  assertAllocationStatus,
  isAllocationTerminalStatus,
  isAllocationNonTerminalStatus,
  isAllocationSuccessTerminalStatus,
  classifyAllocationCardinality,
  type AllocationStatus,
  type AllocationNonTerminalStatus,
  type AllocationTerminalStatus,
  type AllocationSuccessTerminalStatus,
  type AllocationId,
  type AllocationReference,
  type FinancialReference,
  type SourcePaymentId,
  type SourceCheckId,
  type TargetCheckId,
  type AllocationSequence,
  type AllocationPortionId,
  type AllocationAdjustmentId,
  type AllocationReversalId,
  type MultiCheckAllocationIdentity,
  type AllocationSource,
  type AllocationPortion,
  type AllocationTarget,
  type AllocationResponsibility,
  type AllocationRemaining,
  type AllocationCompletion,
  type AllocationAdjustment,
  type AllocationReversal,
  type MultiCheckAllocation,
  type AllocationCardinality,
} from "./multiCheckAllocationContract";

export {
  MultiCheckAllocationDomainError,
  AllocationExceededError,
  InvalidAllocationStateError,
  InvalidAllocationTransitionError,
  IllegalTerminalTransitionError,
  AllocationAlreadyCompletedError,
  AllocationAlreadyCancelledError,
  AllocationAlreadyReversedError,
  FinancialConservationViolationError,
  NegativeResponsibilityError,
  InvalidMoneyAmountError,
  IdentityViolationError,
  DuplicateIdentityError,
  FinalityViolationError,
  PaymentValueExceededError,
  OrderSettlementOwnershipViolationError,
  type MultiCheckAllocationErrorCode,
} from "./multiCheckAllocationErrors";

export {
  parseAllocationMoney,
  formatAllocationMoney,
  moneyEquals,
  moneyAdd,
  moneySub,
  sumPortionAmounts,
  netAdjustmentAmount,
  computeAllocatedAmount,
  computeRemainingAmount,
  assertAllocationConservation,
  assertPortionsWithinResponsibility,
  assertWithinPaymentValueCap,
  assertAllocationSetConservation,
  buildResponsibilitySnapshot,
} from "./multiCheckAllocationMoney";

export {
  getAllowedTransitions,
  isTransitionAllowed,
  assertTransitionAllowed,
  assertNonTerminal,
  canCancel,
  canReserve,
  canApply,
  canAdjust,
  canReverse,
  canComplete,
} from "./multiCheckAllocationLifecycle";

export {
  MULTI_CHECK_ALLOCATION_DOMAIN_EVENT_TYPES,
  eventBaseFromAllocation,
  type MultiCheckAllocationDomainEventType,
  type MultiCheckAllocationDomainEvent,
  type AllocationCreated,
  type AllocationReserved,
  type AllocationApplied,
  type AllocationAdjusted,
  type AllocationReversed,
  type AllocationCompleted,
  type AllocationCancelled,
  type AllocationResponsibilityTransferred,
  type AllocationOutstandingChanged,
} from "./multiCheckAllocationEvents";

export {
  assertAllocationId,
  assertAllocationReference,
  assertFinancialReference,
  assertSourcePaymentId,
  assertAllocationPortionId,
  assertAllocationAdjustmentId,
  assertAllocationReversalId,
  assertAllocationSequence,
  assertCheckId,
  assertMultiCheckAllocationIdentity,
  assertTenantMatch,
  assertUniqueAllocationId,
  assertIdentityUnchanged,
  assertUniquePortionIds,
  assertUniqueSequences,
} from "./multiCheckAllocationIdentity";

export {
  assertAllocationValid,
  assertAllocationFinality,
  assertAllocationIdentityStable,
  assertNoTerminalRegression,
  assertCreateInputs,
  assertMultiCheckAllocationValid,
  assertMoneyAlgebra,
} from "./multiCheckAllocationInvariants";

export {
  createMultiCheckAllocation,
  reserveAllocation,
  applyAllocation,
  adjustAllocation,
  reverseAllocation,
  completeAllocation,
  cancelAllocation,
  assertMultiCheckAllocationSetValid,
  sumAllocatedToTarget,
  moneyAddAllocation,
  moneyEqualsAllocation,
  type MultiCheckAllocationCommandOutcome,
  type MultiCheckAllocationCommandResult,
  type CreateAllocationPortionInput,
  type CreateAllocationSourceInput,
  type CreateMultiCheckAllocationCommand,
  type ReserveAllocationCommand,
  type ApplyAllocationCommand,
  type AdjustAllocationCommand,
  type ReverseAllocationCommand,
  type CompleteAllocationCommand,
  type CancelAllocationCommand,
} from "./multiCheckAllocationCommands";

export {
  MULTI_CHECK_ALLOCATION_PROJECTION_PROGRAM_ID,
  MULTI_CHECK_ALLOCATION_PROJECTION_SCHEMA_VERSION,
  MULTI_CHECK_ALLOCATION_PROJECTION_ID,
  buildMultiCheckAllocationProjectionRevision,
  buildMultiCheckAllocationPortionProjectionRevision,
  buildMultiCheckAllocationAdjustmentProjectionRevision,
  buildMultiCheckAllocationReversalProjectionRevision,
  buildMultiCheckAllocationResponsibilityProjectionRevision,
  buildMultiCheckAllocationPortionProjection,
  buildMultiCheckAllocationAdjustmentProjection,
  buildMultiCheckAllocationReversalProjection,
  buildMultiCheckAllocationResponsibilityProjection,
  buildMultiCheckAllocationSummaryProjection,
  buildMultiCheckAllocationProjection,
  buildMultiCheckAllocationProjections,
  buildMultiCheckAllocationProjectionEventClaimKey,
  isMultiCheckAllocationProjectionSnapshotCoherent,
  assertMultiCheckAllocationProjectionSnapshotCoherent,
  type MultiCheckAllocationCommittedSnapshot,
  type MultiCheckAllocationProjectionSnapshotKey,
  type MultiCheckAllocationProjectionSnapshotStamp,
  type MultiCheckAllocationProjectionBuildOptions,
  type MultiCheckAllocationProjectionTimelineKind,
  type MultiCheckAllocationProjectionTimelineEntry,
  type MultiCheckAllocationProjectionMetadata,
  type MultiCheckAllocationSourceProjection,
  type MultiCheckAllocationTargetProjection,
  type MultiCheckAllocationPortionProjection,
  type MultiCheckAllocationAdjustmentProjection,
  type MultiCheckAllocationReversalProjection,
  type MultiCheckAllocationResponsibilityProjection,
  type MultiCheckAllocationSummaryProjection,
  type MultiCheckAllocationProjection,
  type MultiCheckAllocationProjectionIdentity,
  type MultiCheckAllocationProjectionEventClaimKey,
} from "./projection";
