import type { ReportingExportLanguage } from "./types";

export type ReportingExportLabels = Readonly<{
  brand: string;
  generatedBy: string;
  cover: string;
  reportTitleDefault: string;
  executive: string;
  financial: string;
  operational: string;
  catalog: string;
  orderSalesRollup: string;
  revenueTrend: string;
  revenue: string;
  orderSales: string;
  orderSalesToday: string;
  orderSalesMonth: string;
  paidChecks: string;
  averageCheck: string;
  averageOrder: string;
  averageOrderToday: string;
  averageOrderMonth: string;
  sessionsActive: string;
  orders: string;
  ordersToday: string;
  ordersMonth: string;
  taxCollected: string;
  complimentaryCount: string;
  complimentaryAmount: string;
  voidedCount: string;
  currency: string;
  pricingMode: string;
  taxPolicy: string;
  occupiedTables: string;
  pendingOrders: string;
  kitchenLoad: string;
  activeOrders: string;
  preparingOrders: string;
  readyOrders: string;
  categories: string;
  items: string;
  menuVisits: string;
  topSellersNote: string;
  catalogPlaceholderTitle: string;
  catalogPlaceholderBody: string;
  revenueVsOrderSales: string;
  period: string;
  periodKey: string;
  orderCount: string;
  completedOrders: string;
  paidCheckCount: string;
  generated: string;
  metric: string;
  value: string;
  kpiCards: string;
  chartRevenueTrend: string;
  chartOrderTrend: string;
  printFooter: string;
  confidential: string;
}>;

export function reportingExportLabels(
  language: ReportingExportLanguage
): ReportingExportLabels {
  if (language === "ar") {
    return {
      brand: "MineuQR",
      generatedBy: "تم الإنشاء بواسطة MineuQR",
      cover: "الغلاف",
      reportTitleDefault: "تقرير الأداء التجاري",
      executive: "الملخص التنفيذي",
      financial: "الملخص المالي",
      operational: "الملخص التشغيلي",
      catalog: "الكتالوج",
      orderSalesRollup: "مبيعات الطلبات",
      revenueTrend: "اتجاه الإيرادات",
      revenue: "الإيرادات",
      orderSales: "مبيعات الطلبات",
      orderSalesToday: "مبيعات طلبات اليوم",
      orderSalesMonth: "مبيعات طلبات الشهر",
      paidChecks: "شيكات مدفوعة",
      averageCheck: "متوسط الشيك",
      averageOrder: "متوسط الطلب",
      averageOrderToday: "متوسط طلب اليوم",
      averageOrderMonth: "متوسط طلب الشهر",
      sessionsActive: "جلسات نشطة",
      orders: "الطلبات",
      ordersToday: "طلبات اليوم",
      ordersMonth: "طلبات الشهر",
      taxCollected: "الضريبة المحصّلة",
      complimentaryCount: "شيكات مجانية",
      complimentaryAmount: "مبلغ المجانية",
      voidedCount: "شيكات ملغاة",
      currency: "العملة",
      pricingMode: "وضع التسعير",
      taxPolicy: "سياسة الضريبة",
      occupiedTables: "طاولات مشغولة",
      pendingOrders: "طلبات معلّقة",
      kitchenLoad: "حمل المطبخ",
      activeOrders: "طلبات نشطة",
      preparingOrders: "قيد التحضير",
      readyOrders: "جاهزة",
      categories: "التصنيفات",
      items: "الأصناف",
      menuVisits: "زيارات المنيو",
      topSellersNote:
        "الأصناف الأكثر مبيعاً ستتوفر عبر REPORTING-CATALOG-METRICS-1.",
      catalogPlaceholderTitle: "مقاييس الكتالوج المتقدمة",
      catalogPlaceholderBody:
        "قوائم الأكثر مبيعاً والكميات والمبيعات حسب الصنف غير متاحة بعد. لا يتم حساب مؤشرات مؤقتة في طبقة العرض.",
      revenueVsOrderSales:
        "الإيرادات = شيكات مدفوعة (grand total). مبيعات الطلبات ≠ الإيرادات.",
      period: "الفترة",
      periodKey: "الفترة",
      orderCount: "عدد الطلبات",
      completedOrders: "طلبات مكتملة",
      paidCheckCount: "شيكات مدفوعة",
      generated: "تاريخ الإنشاء",
      metric: "المؤشر",
      value: "القيمة",
      kpiCards: "بطاقات المؤشرات",
      chartRevenueTrend: "مخطط اتجاه الإيرادات",
      chartOrderTrend: "مخطط اتجاه الطلبات",
      printFooter: "MineuQR · تقرير أعمال",
      confidential: "للاستخدام الداخلي",
    };
  }

  return {
    brand: "MineuQR",
    generatedBy: "Generated by MineuQR",
    cover: "Cover",
    reportTitleDefault: "Business Performance Report",
    executive: "Executive Summary",
    financial: "Financial Summary",
    operational: "Operational Summary",
    catalog: "Catalog",
    orderSalesRollup: "Order Sales",
    revenueTrend: "Revenue Trend",
    revenue: "Revenue",
    orderSales: "Order Sales",
    orderSalesToday: "Today's Order Sales",
    orderSalesMonth: "Month Order Sales",
    paidChecks: "Paid Checks",
    averageCheck: "Average Check",
    averageOrder: "Average Order",
    averageOrderToday: "Average Order (Today)",
    averageOrderMonth: "Average Order (Month)",
    sessionsActive: "Active Sessions",
    orders: "Orders",
    ordersToday: "Orders (Today)",
    ordersMonth: "Orders (Month)",
    taxCollected: "Tax Collected",
    complimentaryCount: "Complimentary Checks",
    complimentaryAmount: "Complimentary Amount",
    voidedCount: "Voided Checks",
    currency: "Currency",
    pricingMode: "Pricing Mode",
    taxPolicy: "Tax Policy",
    occupiedTables: "Occupied Tables",
    pendingOrders: "Pending Orders",
    kitchenLoad: "Kitchen Load",
    activeOrders: "Active Orders",
    preparingOrders: "Preparing",
    readyOrders: "Ready",
    categories: "Categories",
    items: "Items",
    menuVisits: "Menu Visits",
    topSellersNote:
      "Top sellers will be provided by REPORTING-CATALOG-METRICS-1.",
    catalogPlaceholderTitle: "Advanced Catalog Metrics",
    catalogPlaceholderBody:
      "Top sellers, quantities, and item-level sales are not available yet. Presentation does not invent temporary KPIs.",
    revenueVsOrderSales:
      "Revenue = Paid Check grand totals. Order Sales ≠ Revenue.",
    period: "Period",
    periodKey: "Period",
    orderCount: "Orders",
    completedOrders: "Completed Orders",
    paidCheckCount: "Paid Checks",
    generated: "Generated",
    metric: "Metric",
    value: "Value",
    kpiCards: "KPI Summary",
    chartRevenueTrend: "Revenue Trend Chart",
    chartOrderTrend: "Order Trend Chart",
    printFooter: "MineuQR · Business Report",
    confidential: "Internal use",
  };
}
