/**
 * REPORTING-EXPORT-TEMPLATES-1 — Enterprise Excel presentation template.
 * Layout / formatting / charts only. Does not calculate Revenue or other KPIs.
 */
import ExcelJS from "exceljs";
import {
  buildExcelCurrencyNumFmt,
  normalizeCurrencyCode,
} from "@/lib/currencyLocale";
import { formatInRestaurantTimezone } from "@/lib/datetime";
import {
  REPORT_THEME,
  bodyFont,
  cellBorder,
  headerFont,
  isRtl,
  metaFont,
  periodFont,
  reportAlignment,
  restaurantFont,
  solidFill,
  titleFont,
} from "@/lib/excel/reportTheme";
import { fetchRestaurantLogoAsset } from "../branding";
import { renderTrendChartPng } from "../charts/renderTrendChartPng";
import {
  formatMoneyDisplay,
  formatNullableCount,
  formatPricingMode,
  formatTaxPolicySummary,
  parseDtoAmountForDisplay,
  resolveExportCurrency,
} from "../format";
import { reportingExportLabels, type ReportingExportLabels } from "../labels";
import type { RestaurantReportingExportBundle } from "../types";

function sanitizeSheetName(name: string): string {
  const cleaned = name.replace(/[\\/?*[\]:]/g, " ").trim() || "Report";
  return cleaned.slice(0, 31);
}

function applyPrintSetup(
  sheet: ExcelJS.Worksheet,
  language: RestaurantReportingExportBundle["language"],
  options?: { landscape?: boolean; freezeAt?: number }
) {
  const rtl = isRtl(language);
  sheet.views = [
    {
      rightToLeft: rtl,
      state: "frozen",
      ySplit: options?.freezeAt ?? 4,
      showGridLines: false,
    },
  ];
  sheet.pageSetup = {
    orientation: options?.landscape ? "landscape" : "portrait",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    paperSize: 9,
    margins: {
      left: 0.5,
      right: 0.5,
      top: 0.6,
      bottom: 0.6,
      header: 0.3,
      footer: 0.3,
    },
    printTitlesRow: "1:4",
  };
  sheet.headerFooter = {
    oddFooter: rtl
      ? "&RGenerated by MineuQR&L&P / &N"
      : "&LGenerated by MineuQR&RPage &P of &N",
  };
}

function styleSectionTitle(
  sheet: ExcelJS.Worksheet,
  row: number,
  colSpan: number,
  text: string,
  language: RestaurantReportingExportBundle["language"]
) {
  sheet.mergeCells(row, 1, row, colSpan);
  const cell = sheet.getCell(row, 1);
  cell.value = text;
  cell.font = titleFont(language);
  cell.alignment = reportAlignment(language, isRtl(language) ? "right" : "left");
  sheet.getRow(row).height = 28;
}

function writeMetaRow(
  sheet: ExcelJS.Worksheet,
  row: number,
  label: string,
  value: string,
  language: RestaurantReportingExportBundle["language"]
) {
  const rtl = isRtl(language);
  sheet.getCell(row, 1).value = label;
  sheet.getCell(row, 1).font = metaFont(language);
  sheet.getCell(row, 1).alignment = reportAlignment(
    language,
    rtl ? "right" : "left"
  );
  sheet.getCell(row, 2).value = value;
  sheet.getCell(row, 2).font = bodyFont(language, true);
  sheet.getCell(row, 2).alignment = reportAlignment(
    language,
    rtl ? "right" : "left"
  );
}

function writeStyledTable(
  sheet: ExcelJS.Worksheet,
  startRow: number,
  headers: string[],
  dataRows: ReadonlyArray<ReadonlyArray<string | number>>,
  language: RestaurantReportingExportBundle["language"],
  currencyCols: ReadonlySet<number>,
  currencyFmt: string
): number {
  const headerRow = sheet.getRow(startRow);
  headers.forEach((text, col) => {
    const cell = headerRow.getCell(col + 1);
    cell.value = text;
    cell.font = headerFont(language);
    cell.fill = solidFill(REPORT_THEME.headerBg);
    cell.alignment = reportAlignment(language, "center");
    cell.border = cellBorder(REPORT_THEME.borderLight);
  });
  headerRow.height = 26;

  dataRows.forEach((values, index) => {
    const row = sheet.getRow(startRow + 1 + index);
    const fill = solidFill(
      index % 2 === 1 ? REPORT_THEME.zebra : REPORT_THEME.white
    );
    values.forEach((value, col) => {
      const cell = row.getCell(col + 1);
      cell.value = value;
      cell.font = bodyFont(language);
      cell.fill = fill;
      cell.border = cellBorder(REPORT_THEME.borderLight);
      cell.alignment = reportAlignment(language, "center");
      if (typeof value === "number") {
        cell.numFmt = currencyCols.has(col) ? currencyFmt : "#,##0";
      }
    });
    row.height = 22;
  });

  headers.forEach((_, i) => {
    const col = sheet.getColumn(i + 1);
    let maxLen = String(headers[i] ?? "").length;
    for (const row of dataRows) {
      const len = String(row[i] ?? "").length;
      if (len > maxLen) maxLen = len;
    }
    col.width = Math.min(42, Math.max(12, maxLen + 4));
  });

  return startRow + 1 + dataRows.length;
}

function writeKpiCards(
  sheet: ExcelJS.Worksheet,
  startRow: number,
  cards: ReadonlyArray<readonly [string, string]>,
  language: RestaurantReportingExportBundle["language"]
): number {
  const rtl = isRtl(language);
  const cols = 3;
  let row = startRow;
  for (let i = 0; i < cards.length; i += cols) {
    for (let c = 0; c < cols; c++) {
      const card = cards[i + c];
      if (!card) continue;
      const col = c * 2 + 1;
      const labelCell = sheet.getCell(row, col);
      const valueCell = sheet.getCell(row + 1, col);
      sheet.mergeCells(row, col, row, col + 1);
      sheet.mergeCells(row + 1, col, row + 1, col + 1);

      labelCell.value = card[0];
      labelCell.font = metaFont(language);
      labelCell.fill = solidFill(REPORT_THEME.brandBanner);
      labelCell.border = cellBorder(REPORT_THEME.borderLight);
      labelCell.alignment = reportAlignment(language, rtl ? "right" : "left", 1);

      valueCell.value = card[1];
      valueCell.font = {
        ...restaurantFont(language),
        size: 14,
        color: { argb: REPORT_THEME.brandDark },
      };
      valueCell.fill = solidFill(REPORT_THEME.white);
      valueCell.border = cellBorder(REPORT_THEME.border);
      valueCell.alignment = reportAlignment(language, rtl ? "right" : "left", 1);
    }
    sheet.getRow(row).height = 18;
    sheet.getRow(row + 1).height = 26;
    row += 3;
  }
  return row;
}

async function maybeAddChartImage(
  workbook: ExcelJS.Workbook,
  sheet: ExcelJS.Worksheet,
  anchorCol: number,
  anchorRow: number,
  title: string,
  categories: readonly string[],
  series: ReadonlyArray<{ label: string; values: readonly number[] }>
) {
  if (categories.length === 0) return;
  const png = await renderTrendChartPng({ title, categories, series });
  if (!png) return;
  const imageId = workbook.addImage({
    buffer: png as unknown as ExcelJS.Buffer,
    extension: "png",
  });
  sheet.addImage(imageId, {
    tl: { col: anchorCol, row: anchorRow },
    ext: { width: 640, height: 280 },
  });
}

export async function buildReportingExportWorkbook(
  bundle: RestaurantReportingExportBundle,
  fallbackCurrencySymbol: string,
  fallbackCurrencyCode?: string
): Promise<ExcelJS.Workbook> {
  const labels = reportingExportLabels(bundle.language);
  const { currencySymbol, currencyCode } = resolveExportCurrency(
    bundle.business,
    fallbackCurrencySymbol,
    fallbackCurrencyCode
  );
  const currencyFmt = buildExcelCurrencyNumFmt({
    language: bundle.language,
    currencyCode: normalizeCurrencyCode(currencyCode, currencySymbol),
    currencySymbol,
    decimalPlaces: 2,
  });

  const workbook = new ExcelJS.Workbook();
  workbook.creator = "MineuQR";
  workbook.lastModifiedBy = "MineuQR";
  workbook.created = new Date();
  workbook.modified = new Date();
  workbook.title = bundle.reportTitle || labels.reportTitleDefault;
  workbook.subject = "Business Performance Report";
  workbook.keywords = "MineuQR,Reporting,Revenue,Order Sales";

  const generated = formatInRestaurantTimezone(
    new Date(),
    bundle.language === "ar" ? "ar-SA" : "en-GB",
    { dateStyle: "medium", timeStyle: "short" }
  );

  const money = (amount: string) => formatMoneyDisplay(amount, currencySymbol);
  const biz = bundle.business;
  const sales = bundle.orderSales;
  const ops = bundle.operational;
  const catalog = bundle.catalog;
  const reportTitle = bundle.reportTitle?.trim() || labels.reportTitleDefault;
  const logo = await fetchRestaurantLogoAsset(bundle.logoUrl);

  buildCoverSheet(workbook, {
    bundle,
    labels,
    reportTitle,
    generated,
    currencyCode,
    currencySymbol,
    logo,
  });

  buildExecutiveSheet(workbook, {
    bundle,
    labels,
    money,
    generated,
  });

  buildFinancialSheet(workbook, {
    bundle,
    labels,
    money,
    currencyCode,
    currencySymbol,
    currencyFmt,
  });

  buildOperationalSheet(workbook, { bundle, labels });
  buildCatalogSheet(workbook, { bundle, labels });

  await buildRevenueTrendSheet(workbook, {
    bundle,
    labels,
    currencyFmt,
  });

  await buildOrderSalesSheet(workbook, {
    bundle,
    labels,
    currencyFmt,
  });

  return workbook;
}

function buildCoverSheet(
  workbook: ExcelJS.Workbook,
  ctx: {
    bundle: RestaurantReportingExportBundle;
    labels: ReportingExportLabels;
    reportTitle: string;
    generated: string;
    currencyCode: string;
    currencySymbol: string;
    logo: Awaited<ReturnType<typeof fetchRestaurantLogoAsset>>;
  }
) {
  const { bundle, labels, reportTitle, generated, currencyCode, currencySymbol, logo } =
    ctx;
  const sheet = workbook.addWorksheet(sanitizeSheetName(labels.cover));
  const lang = bundle.language;

  sheet.getColumn(1).width = 28;
  sheet.getColumn(2).width = 42;
  sheet.getColumn(3).width = 22;

  let row = 1;
  if (logo) {
    const imageId = workbook.addImage({
      buffer: logo.buffer as unknown as ExcelJS.Buffer,
      extension: logo.extension,
    });
    sheet.addImage(imageId, {
      tl: { col: 0, row: 0 },
      ext: { width: 96, height: 96 },
    });
    row = 7;
  }

  sheet.mergeCells(row, 1, row, 3);
  sheet.getCell(row, 1).value = labels.brand;
  sheet.getCell(row, 1).font = {
    ...bodyFont(lang, true),
    size: 11,
    color: { argb: REPORT_THEME.brandDark },
  };
  row += 1;

  sheet.mergeCells(row, 1, row, 3);
  sheet.getCell(row, 1).value = bundle.restaurantName || "—";
  sheet.getCell(row, 1).font = {
    ...restaurantFont(lang),
    size: 20,
  };
  sheet.getRow(row).height = 28;
  row += 2;

  sheet.mergeCells(row, 1, row, 3);
  sheet.getCell(row, 1).value = reportTitle;
  sheet.getCell(row, 1).font = titleFont(lang);
  sheet.getRow(row).height = 32;
  row += 2;

  writeMetaRow(sheet, row++, labels.period, bundle.periodLabel, lang);
  writeMetaRow(sheet, row++, labels.generated, generated, lang);
  writeMetaRow(
    sheet,
    row++,
    labels.currency,
    `${currencyCode} (${currencySymbol})`,
    lang
  );
  writeMetaRow(
    sheet,
    row++,
    labels.pricingMode,
    formatPricingMode(bundle.business, lang),
    lang
  );
  writeMetaRow(
    sheet,
    row++,
    labels.taxPolicy,
    formatTaxPolicySummary(bundle.business, lang),
    lang
  );
  row += 1;
  writeMetaRow(sheet, row++, labels.confidential, labels.generatedBy, lang);

  const banner = sheet.getCell(row + 1, 1);
  sheet.mergeCells(row + 1, 1, row + 1, 3);
  banner.value = labels.revenueVsOrderSales;
  banner.font = periodFont(lang);
  banner.fill = solidFill(REPORT_THEME.brandLight);
  banner.alignment = reportAlignment(lang, isRtl(lang) ? "right" : "left", 1);

  applyPrintSetup(sheet, lang, { freezeAt: 0 });
  sheet.views = [{ rightToLeft: isRtl(lang), showGridLines: false }];
}

function buildExecutiveSheet(
  workbook: ExcelJS.Workbook,
  ctx: {
    bundle: RestaurantReportingExportBundle;
    labels: ReportingExportLabels;
    money: (amount: string) => string;
    generated: string;
  }
) {
  const { bundle, labels, money, generated } = ctx;
  const sheet = workbook.addWorksheet(sanitizeSheetName(labels.executive));
  const lang = bundle.language;
  const biz = bundle.business;
  const sales = bundle.orderSales;
  const ops = bundle.operational;

  styleSectionTitle(sheet, 1, 6, labels.executive, lang);
  sheet.getCell(2, 1).value = `${labels.period}: ${bundle.periodLabel}`;
  sheet.getCell(2, 1).font = periodFont(lang);
  sheet.getCell(3, 1).value = `${labels.generated}: ${generated}`;
  sheet.getCell(3, 1).font = metaFont(lang);

  writeKpiCards(
    sheet,
    5,
    [
      [labels.revenue, money(biz.revenue)],
      [labels.orderSalesMonth, money(sales.month.orderSales)],
      [labels.paidChecks, String(biz.paidCheckCount)],
      [labels.averageCheck, money(biz.averageCheck)],
      [labels.averageOrderMonth, money(sales.month.averageOrder)],
      [labels.sessionsActive, String(ops.activeSessions)],
      [labels.ordersMonth, String(sales.month.totalOrders)],
      [labels.orderSalesToday, money(sales.today.orderSales)],
      [labels.ordersToday, String(sales.today.totalOrders)],
    ],
    lang
  );

  for (let c = 1; c <= 6; c++) sheet.getColumn(c).width = 16;
  applyPrintSetup(sheet, lang, { landscape: true, freezeAt: 4 });
}

function buildFinancialSheet(
  workbook: ExcelJS.Workbook,
  ctx: {
    bundle: RestaurantReportingExportBundle;
    labels: ReportingExportLabels;
    money: (amount: string) => string;
    currencyCode: string;
    currencySymbol: string;
    currencyFmt: string;
  }
) {
  const { bundle, labels, money, currencyCode, currencySymbol, currencyFmt } =
    ctx;
  const sheet = workbook.addWorksheet(sanitizeSheetName(labels.financial));
  const lang = bundle.language;
  const biz = bundle.business;
  const sales = bundle.orderSales;

  styleSectionTitle(sheet, 1, 3, labels.financial, lang);
  sheet.mergeCells(2, 1, 2, 3);
  sheet.getCell(2, 1).value = labels.revenueVsOrderSales;
  sheet.getCell(2, 1).font = periodFont(lang);
  sheet.getCell(2, 1).fill = solidFill(REPORT_THEME.brandLight);

  writeStyledTable(
    sheet,
    4,
    [labels.metric, labels.value, ""],
    [
      [labels.revenue, money(biz.revenue), ""],
      [labels.taxCollected, money(biz.taxCollected), ""],
      [labels.complimentaryCount, String(biz.complimentaryCount), ""],
      [labels.complimentaryAmount, money(biz.complimentaryAmount), ""],
      [labels.voidedCount, String(biz.voidedCount), ""],
      [labels.currency, `${currencyCode} (${currencySymbol})`, ""],
      [labels.pricingMode, formatPricingMode(biz, lang), ""],
      [labels.taxPolicy, formatTaxPolicySummary(biz, lang), ""],
      [labels.orderSalesMonth, money(sales.month.orderSales), ""],
      [labels.orderSalesToday, money(sales.today.orderSales), ""],
    ],
    lang,
    new Set(),
    currencyFmt
  );

  applyPrintSetup(sheet, lang, { freezeAt: 4 });
}

function buildOperationalSheet(
  workbook: ExcelJS.Workbook,
  ctx: {
    bundle: RestaurantReportingExportBundle;
    labels: ReportingExportLabels;
  }
) {
  const { bundle, labels } = ctx;
  const sheet = workbook.addWorksheet(sanitizeSheetName(labels.operational));
  const lang = bundle.language;
  const ops = bundle.operational;

  styleSectionTitle(sheet, 1, 2, labels.operational, lang);
  writeStyledTable(
    sheet,
    3,
    [labels.metric, labels.value],
    [
      [labels.sessionsActive, String(ops.activeSessions)],
      [labels.occupiedTables, String(ops.occupiedTables)],
      [labels.pendingOrders, String(ops.pendingOrders)],
      [labels.kitchenLoad, String(ops.kitchenLoad)],
      [labels.activeOrders, formatNullableCount(ops.activeOrders)],
      [labels.preparingOrders, formatNullableCount(ops.preparingOrders)],
      [labels.readyOrders, formatNullableCount(ops.readyOrders)],
    ],
    lang,
    new Set(),
    "#,##0"
  );
  applyPrintSetup(sheet, lang, { freezeAt: 3 });
}

function buildCatalogSheet(
  workbook: ExcelJS.Workbook,
  ctx: {
    bundle: RestaurantReportingExportBundle;
    labels: ReportingExportLabels;
  }
) {
  const { bundle, labels } = ctx;
  const sheet = workbook.addWorksheet(sanitizeSheetName(labels.catalog));
  const lang = bundle.language;
  const catalog = bundle.catalog;

  styleSectionTitle(sheet, 1, 2, labels.catalog, lang);
  writeStyledTable(
    sheet,
    3,
    [labels.metric, labels.value],
    [
      [labels.categories, String(catalog.categoryCount)],
      [labels.items, String(catalog.itemCount)],
      [labels.menuVisits, String(catalog.menuVisits)],
    ],
    lang,
    new Set(),
    "#,##0"
  );

  sheet.mergeCells(8, 1, 8, 2);
  sheet.getCell(8, 1).value = labels.catalogPlaceholderTitle;
  sheet.getCell(8, 1).font = restaurantFont(lang);
  sheet.mergeCells(9, 1, 10, 2);
  sheet.getCell(9, 1).value = labels.catalogPlaceholderBody;
  sheet.getCell(9, 1).font = periodFont(lang);
  sheet.getCell(9, 1).fill = solidFill(REPORT_THEME.brandBanner);
  sheet.getCell(9, 1).alignment = {
    ...reportAlignment(lang, isRtl(lang) ? "right" : "left", 1),
    wrapText: true,
    vertical: "top",
  };
  sheet.getRow(9).height = 48;

  sheet.mergeCells(12, 1, 12, 2);
  sheet.getCell(12, 1).value = labels.topSellersNote;
  sheet.getCell(12, 1).font = metaFont(lang);

  applyPrintSetup(sheet, lang, { freezeAt: 3 });
}

async function buildRevenueTrendSheet(
  workbook: ExcelJS.Workbook,
  ctx: {
    bundle: RestaurantReportingExportBundle;
    labels: ReportingExportLabels;
    currencyFmt: string;
  }
) {
  const { bundle, labels, currencyFmt } = ctx;
  const sheet = workbook.addWorksheet(sanitizeSheetName(labels.revenueTrend));
  const lang = bundle.language;
  const points = bundle.revenueTrend.points;

  styleSectionTitle(sheet, 1, 4, labels.revenueTrend, lang);
  sheet.getCell(2, 1).value = labels.chartRevenueTrend;
  sheet.getCell(2, 1).font = periodFont(lang);

  const end = writeStyledTable(
    sheet,
    4,
    [
      labels.periodKey,
      labels.paidCheckCount,
      labels.revenue,
      labels.taxCollected,
    ],
    points.map((p) => [
      p.periodKey,
      p.paidCheckCount,
      parseDtoAmountForDisplay(p.revenue),
      parseDtoAmountForDisplay(p.taxCollected),
    ]),
    lang,
    new Set([2, 3]),
    currencyFmt
  );

  await maybeAddChartImage(
    workbook,
    sheet,
    0,
    end + 1,
    labels.chartRevenueTrend,
    points.map((p) => p.periodKey),
    [
      {
        label: labels.revenue,
        values: points.map((p) => parseDtoAmountForDisplay(p.revenue)),
      },
    ]
  );

  applyPrintSetup(sheet, lang, { landscape: true, freezeAt: 4 });
}

async function buildOrderSalesSheet(
  workbook: ExcelJS.Workbook,
  ctx: {
    bundle: RestaurantReportingExportBundle;
    labels: ReportingExportLabels;
    currencyFmt: string;
  }
) {
  const { bundle, labels, currencyFmt } = ctx;
  const sheet = workbook.addWorksheet(sanitizeSheetName(labels.orderSalesRollup));
  const lang = bundle.language;
  const periods = bundle.orderSalesRollup.periods;

  styleSectionTitle(sheet, 1, 4, labels.orderSalesRollup, lang);
  sheet.mergeCells(2, 1, 2, 4);
  sheet.getCell(2, 1).value = labels.revenueVsOrderSales;
  sheet.getCell(2, 1).font = periodFont(lang);
  sheet.getCell(2, 1).fill = solidFill(REPORT_THEME.brandLight);

  const end = writeStyledTable(
    sheet,
    4,
    [
      labels.periodKey,
      labels.orderCount,
      labels.completedOrders,
      labels.orderSales,
    ],
    periods.map((p) => [
      p.periodKey,
      p.orderCount,
      p.completedOrders,
      parseDtoAmountForDisplay(p.orderSales),
    ]),
    lang,
    new Set([3]),
    currencyFmt
  );

  await maybeAddChartImage(
    workbook,
    sheet,
    0,
    end + 1,
    labels.chartOrderTrend,
    periods.map((p) => p.periodKey),
    [
      {
        label: labels.orderSales,
        values: periods.map((p) => parseDtoAmountForDisplay(p.orderSales)),
      },
      {
        label: labels.orderCount,
        values: periods.map((p) => p.orderCount),
      },
    ]
  );

  applyPrintSetup(sheet, lang, { landscape: true, freezeAt: 4 });
}
