/**
 * SPLIT-PAYMENT-DOMAIN-1 — pure Split Payment domain barrel.
 * ADR-ARCH-024 · Check-owned FSP capability · NOT an Aggregate Root · no persistence.
 */

export {
  SPLIT_PAYMENT_PROGRAM_ID,
  SPLIT_PAYMENT_ADR_ID,
  SPLIT_PAYMENT_STATUSES,
  SPLIT_PAYMENT_NON_TERMINAL_STATUSES,
  SPLIT_PAYMENT_TERMINAL_STATUSES,
  SPLIT_PAYMENT_SUCCESS_TERMINAL_STATUSES,
  SPLIT_PAYMENT_VALUE_RECEIVED_STATUSES,
  TENDER_METHODS,
  isSplitPaymentStatus,
  assertSplitPaymentStatus,
  isSplitPaymentTerminalStatus,
  isSplitPaymentNonTerminalStatus,
  isValueReceivedStatus,
  isTenderMethod,
  type SplitPaymentStatus,
  type SplitPaymentNonTerminalStatus,
  type SplitPaymentTerminalStatus,
  type TenderMethod,
  type PaymentId,
  type PaymentAttemptId,
  type TenderId,
  type TenderAllocationId,
  type PaymentAllocationId,
  type PaymentReference,
  type FinancialReference,
  type SplitPaymentIdentity,
  type Tender,
  type TenderAllocation,
  type PaymentPortion,
  type SettlementPortion,
  type PaymentAllocation,
  type OutstandingPortion,
  type PaymentCompletion,
  type FinancialCompletion,
  type SplitPayment,
  type PaymentAttempt,
  type PaymentAttemptStatus,
  type CheckFinancialResponsibility,
} from "./splitPaymentContract";

export {
  SplitPaymentDomainError,
  InvalidPaymentStateError,
  AllocationExceededError,
  OutstandingNegativeError,
  TenderMismatchError,
  PaymentAlreadyCompletedError,
  PaymentAlreadyCancelledError,
  PaymentAlreadyVoidedError,
  InvalidTransitionError,
  IllegalTerminalTransitionError,
  FinancialConservationViolationError,
  InvalidMoneyAmountError,
  PaymentExceedsOutstandingError,
  IdentityViolationError,
  FinalityViolationError,
  DuplicateIdentityError,
  type SplitPaymentErrorCode,
} from "./splitPaymentErrors";

export {
  parseSplitPaymentMoney,
  formatSplitPaymentMoney,
  moneyEquals,
  moneyAdd,
  moneySub,
  calculateOutstandingBalance,
  buildCheckFinancialResponsibility,
  assertCheckConservation,
  sumTenderAmounts,
  assertTenderTotalsMatchPayment,
  assertAllocationWithinPayment,
  assertPaymentWithinOutstanding,
  computeUnallocated,
  assertPaymentMoneyAlgebra,
} from "./splitPaymentMoney";

export {
  getAllowedTransitions,
  isTransitionAllowed,
  assertTransitionAllowed,
  assertNonTerminal,
  canCancel,
  canVoid,
  canRefund,
} from "./splitPaymentLifecycle";

export {
  SPLIT_PAYMENT_DOMAIN_EVENT_TYPES,
  eventBaseFromPayment,
  type SplitPaymentDomainEventType,
  type SplitPaymentDomainEvent,
  type PaymentCreated,
  type PaymentAuthorized,
  type PaymentCaptured,
  type PaymentPartiallyApplied,
  type PaymentApplied,
  type PaymentCompleted,
  type PaymentCancelled,
  type PaymentVoided,
  type PaymentRefunded,
  type PaymentFailed,
  type TenderAllocated,
  type OutstandingUpdated,
  type PaymentAttemptStarted,
  type PaymentAttemptSucceeded,
  type PaymentAttemptFailed,
  type PaymentAttemptCancelled,
} from "./splitPaymentEvents";

export {
  assertPaymentId,
  assertPaymentAttemptId,
  assertTenderAllocationId,
  assertPaymentReference,
  assertFinancialReference,
  assertSplitPaymentIdentity,
  assertTenantMatch,
  assertUniquePaymentId,
  assertUniquePaymentAttemptId,
  assertIdentityUnchanged,
  assertAttemptTraceableToPayment,
} from "./splitPaymentIdentity";

export {
  assertPaymentValid,
  assertOutstandingInvariants,
  assertPaymentRespectsOutstanding,
  assertAllocationInvariants,
  assertPaymentFinality,
  assertNoMoneyInvention,
  assertNoTerminalRegression,
  assertPaymentIdentityStable,
  assertCreateInputs,
  assertSplitPaymentValid,
  assertTendersBelongToPayment,
  isPaymentCompleted,
  isPaymentTerminal,
} from "./splitPaymentInvariants";

export {
  createSplitPayment,
  authorizePayment,
  capturePayment,
  failPayment,
  allocatePayment,
  allocateTenders,
  cancelPayment,
  voidPayment,
  refundPayment,
  updateOutstandingSnapshot,
  startPaymentAttempt,
  succeedPaymentAttempt,
  failPaymentAttempt,
  cancelPaymentAttempt,
  paymentTenderTotal,
  type SplitPaymentCommandOutcome,
  type SplitPaymentCommandResult,
  type PaymentAttemptCommandResult,
  type CreateSplitPaymentCommand,
  type AuthorizePaymentCommand,
  type CapturePaymentCommand,
  type FailPaymentCommand,
  type AllocatePaymentCommand,
  type AllocateTendersCommand,
  type CancelPaymentCommand,
  type VoidPaymentCommand,
  type RefundPaymentCommand,
  type UpdateOutstandingCommand,
  type UpdateOutstandingResult,
  type StartPaymentAttemptCommand,
  type SucceedPaymentAttemptCommand,
  type FailPaymentAttemptCommand,
  type CancelPaymentAttemptCommand,
} from "./splitPaymentCommands";
