/**
 * POS-CASHIER-WORKSPACE-IMPLEMENTATION-1
 * Presentation copy only. Not a permission catalog. Not plan entitlements.
 * CASHIER-PAYMENT-FLOW-IMPLEMENTATION-1 — cashier-facing strings stay inside
 * the Cashier workspace. Internal Check / Bill / Settlement names are not UX.
 */

export type CashierLang = "ar" | "en";

const COPY: Record<string, { ar: string; en: string }> = {
  title: { ar: "الكاشير", en: "Cashier" },
  subtitle: {
    ar: "بيع مباشر أو مراجعة طلب وارد. الصندوق المالي يبقى في عمليات الصندوق.",
    en: "Direct sale or incoming order review. Financial register work stays in Register Ops.",
  },
  terminal: { ar: "الجهاز", en: "Terminal" },
  selectTerminal: { ar: "اختر جهاز نقطة البيع", en: "Select a POS terminal" },
  noTerminal: {
    ar: "لا يوجد جهاز نقطة بيع نشط لهذا المطعم.",
    en: "No active POS terminal for this restaurant.",
  },
  createTerminal: { ar: "إنشاء جهاز نقطة بيع", en: "Create POS terminal" },
  activateTerminal: { ar: "تفعيل جهاز نقطة بيع", en: "Activate POS terminal" },
  terminalListDenied: {
    ar: "لا يمكن عرض الأجهزة. الكاشير يحتاج جهازًا محددًا وصلاحية POS_ACCESS.",
    en: "Terminals cannot be listed. Cashier needs a terminal and POS_ACCESS.",
  },
  accessDenied: {
    ar: "الدخول للوحة المطعم لا يمنح صلاحية الكاشير. يلزم POS_ACCESS وجهاز نشط.",
    en: "Dashboard access is not cashier access. POS_ACCESS and an active terminal are required.",
  },
  enableAccess: {
    ar: "تفعيل صلاحيات الكاشير لحسابي",
    en: "Enable cashier access for my account",
  },
  enableAccessHint: {
    ar: "يستخدم أمر المنح الحالي. ليس نظام الموظفين. لا يُفعَّل تلقائيًا.",
    en: "Uses the existing grant command. Not Staff Access. Not automatic.",
  },
  catalog: { ar: "القائمة", en: "Catalog" },
  allCategories: { ar: "الكل", en: "All" },
  unknownCategory: { ar: "بدون تصنيف", en: "Uncategorized" },
  unavailable: { ar: "غير متاح", en: "Unavailable" },
  saleInvoice: { ar: "فاتورة البيع", en: "Sale / Invoice" },
  invoiceNew: { ar: "فاتورة جديدة", en: "New invoice" },
  invoiceLineTotal: { ar: "إجمالي الصنف", en: "Line total" },
  ticket: { ar: "فاتورة البيع", en: "Sale / Invoice" },
  ticketEmpty: { ar: "اختر أصنافًا من القائمة.", en: "Select items from the catalog." },
  ticketTotal: { ar: "الإجمالي", en: "Total" },
  qty: { ar: "الكمية", en: "Qty" },
  placeSale: { ar: "الدفع", en: "Payment" },
  placing: { ar: "جاري فتح الدفع…", en: "Opening payment…" },
  activeOrders: { ar: "الطلبات النشطة", en: "Active orders" },
  noOrders: { ar: "لا توجد طلبات نشطة.", en: "No active orders." },
  orderDetail: { ar: "تفاصيل الطلب", en: "Order detail" },
  orderCreated: { ar: "الطلب", en: "Order" },
  timeline: { ar: "الخط الزمني", en: "Timeline" },
  checkout: { ar: "الدفع", en: "Checkout" },
  checkLabel: { ar: "الشيك", en: "Check" },
  checkOpenedResult: { ar: "الشيك مفتوح", en: "Check is open" },
  checkMissing: {
    ar: "افتح الشيك لعرض المبلغ المستحق قبل الدفع.",
    en: "Open the check to show the amount due before payment.",
  },
  amountDue: { ar: "المبلغ المستحق", en: "Amount due" },
  orderTotalHint: {
    ar: "بانتظار المبلغ المستحق.",
    en: "Waiting for the amount due.",
  },
  selectPaymentMethod: { ar: "اختر طريقة الدفع", en: "Select payment method" },
  paymentMethod: { ar: "طريقة الدفع", en: "Payment method" },
  completePayment: { ar: "إتمام الدفع", en: "Complete payment" },
  paying: { ar: "جاري الدفع…", en: "Paying…" },
  paidTitle: { ar: "تم الدفع", en: "Payment successful" },
  paidBody: {
    ar: "تم الدفع. يمكنك بدء بيع جديد.",
    en: "Payment is complete. You can start a new sale.",
  },
  afterPayment: {
    ar: "التقارير تقرأ الشيك المدفوع. لا يُحسب إيراد منفصل للكاشير.",
    en: "Reporting reads the paid Check. Cashier does not store a separate revenue total.",
  },
  newSale: { ar: "بيع جديد", en: "New sale" },
  settlement: { ar: "التسوية", en: "Settlement" },
  noSettlement: { ar: "لا توجد تسوية معروضة لهذا الطلب.", en: "No settlement projection for this order." },
  intakeCheck: { ar: "فتح شيك", en: "Open check" },
  initiateSettlement: { ar: "بدء التسوية", en: "Initiate settlement" },
  notes: { ar: "ملاحظات", en: "Notes" },
  modifiers: { ar: "إضافات", en: "Modifiers" },
  loading: { ar: "جاري التحميل…", en: "Loading…" },
  retry: { ar: "إعادة المحاولة", en: "Retry" },
  saleRetrySameItems: {
    ar: "أعد الدفع بنفس الأصناف. لا تغيّر الفاتورة قبل اكتمال المحاولة السابقة.",
    en: "Retry Payment with the same items. Do not change the invoice until the previous attempt finishes.",
  },
  errorTitle: { ar: "تعذر تحميل الكاشير", en: "Cashier could not load" },
  emptyCatalog: { ar: "لا توجد أصناف متاحة.", en: "No available items." },
  salePlaced: { ar: "جاهز للدفع", en: "Ready to pay" },
  unpaidOrderHint: {
    ar: "الطلب مؤكد ولم يُدفع بعد.",
    en: "Order confirmed — unpaid.",
  },
  checkAmountDue: { ar: "المبلغ المستحق من الشيك", en: "Check amount due" },
  checkSettledAmount: { ar: "المدفوع على الشيك", en: "Check settled" },
  checkOpened: { ar: "تم فتح الشيك", en: "Check opened" },
  settlementStarted: { ar: "تم دفع الشيك", en: "Check paid" },
  settlementGap: {
    ar: "التسوية المالية الكاملة قد تتطلب وردية صندوق مفتوحة من عمليات الصندوق.",
    en: "Full paid settlement may require an open register shift from Register Ops.",
  },
  shiftRequired: {
    ar: "لا يمكن إتمام الدفع بدون وردية مالية مفتوحة. افتح الوردية من عمليات الصندوق ثم عد إلى الكاشير.",
    en: "Payment cannot complete without an open financial shift. Open the shift in Register Ops, then return to Cashier.",
  },
  registerRequired: {
    ar: "لا يمكن إتمام الدفع بدون صندوق مفتوح. الصندوق يبقى في عمليات الصندوق.",
    en: "Payment cannot complete without an open register. Register work stays in Register Ops.",
  },
  registerClosed: {
    ar: "الصندوق غير مفتوح. افتح الصندوق من عمليات الصندوق ثم أتمم الدفع هنا.",
    en: "The register is not open. Open it in Register Ops, then complete payment here.",
  },
  openRegisterOps: { ar: "فتح عمليات الصندوق", en: "Open Register Ops" },
  returnDashboard: { ar: "العودة إلى لوحة التحكم", en: "Return to Dashboard" },
  openNewTab: { ar: "فتح الكاشير في تبويب جديد", en: "Open Cashier in a new tab" },
  newTabBlocked: {
    ar: "تعذر فتح تبويب جديد. استخدم الكاشير في هذه النافذة.",
    en: "A new tab could not be opened. Continue in this window.",
  },
  statusReady: { ar: "جاهز", en: "Ready" },
  statusShift: { ar: "يلزم وردية الصندوق", en: "Register shift required" },
  statusAwaitingPayment: { ar: "بانتظار الدفع", en: "Awaiting payment" },
  ticketSubtotal: { ar: "المجموع الفرعي", en: "Subtotal" },
  ticketDiscount: { ar: "الخصم", en: "Discount" },
  applyDiscount: { ar: "خصم", en: "Discount" },
  discountAmount: { ar: "مبلغ الخصم", en: "Discount amount" },
  applyDiscountAction: { ar: "تطبيق", en: "Apply" },
  clearDiscount: { ar: "إزالة", en: "Clear" },
  discountExceeds: {
    ar: "الخصم لا يمكن أن يتجاوز المجموع الفرعي.",
    en: "Discount cannot exceed the subtotal.",
  },
  tenderCash: { ar: "نقدًا", en: "Cash" },
  tenderNetwork: { ar: "شبكة", en: "Network" },
  tenderMixed: { ar: "تسوية", en: "Mixed" },
  tenderComplimentary: { ar: "ضيافة", en: "Complimentary" },
  complimentaryConfirmHint: {
    ar: "تأكيد الضيافة من الكاشير يسجّل التحصيل صفراً. الجلسة لا تُغلق تلقائياً.",
    en: "Cashier complimentary Confirm records zero collection. The session does not close automatically.",
  },
  verifyingAmount: {
    ar: "جاري التحقق من المبلغ المستحق…",
    en: "Verifying amount due…",
  },
  ticketTax: { ar: "الضريبة", en: "Tax" },
  taxAtPayment: { ar: "عند الدفع", en: "At payment" },
  paymentTax: { ar: "الضريبة", en: "Tax" },
  preparingPayment: { ar: "جاري تجهيز الدفع…", en: "Preparing payment…" },
  amountDueMissing: {
    ar: "المبلغ المستحق غير جاهز.",
    en: "Amount due is not ready.",
  },
  collectedAmount: { ar: "المدفوع", en: "Collected" },
  removeLine: { ar: "حذف الصنف", en: "Remove item" },
  completePaymentTitle: { ar: "إتمام الدفع", en: "Complete payment" },
  amountReceived: { ar: "المبلغ المدفوع", en: "Amount received" },
  changeDue: { ar: "الباقي للعميل", en: "Change" },
  confirmPayment: { ar: "تأكيد الدفع", en: "Confirm payment" },
  paidSuccess: { ar: "تم الدفع بنجاح", en: "Payment successful" },
  printInvoice: { ar: "طباعة الفاتورة", en: "Print invoice" },
  receiptTitle: { ar: "فاتورة مدفوعة", en: "Paid receipt" },
  receiptItems: { ar: "الأصناف", en: "Items" },
  receiptClose: { ar: "إغلاق", en: "Close" },
  receiptInvoiceNumber: { ar: "فاتورة رقم", en: "Invoice" },
  receiptDate: { ar: "التاريخ", en: "Date" },
  receiptTime: { ar: "الوقت", en: "Time" },
  receiptCashier: { ar: "الكاشير", en: "Cashier" },
  receiptQty: { ar: "الكمية", en: "Qty" },
  receiptUnitPrice: { ar: "السعر", en: "Price" },
  receiptVat: { ar: "الضريبة VAT", en: "VAT" },
  receiptPaidStamp: { ar: "مدفوعة", en: "Paid" },
  printUnavailable: {
    ar: "الفاتورة غير جاهزة للطباعة بعد.",
    en: "The receipt isn't ready to print yet.",
  },
  shiftBeforePay: {
    ar: "يجب فتح وردية الصندوق قبل إتمام الدفع",
    en: "Open a register shift before completing payment",
  },
  cashInsufficient: {
    ar: "المبلغ المدفوع أقل من المستحق.",
    en: "Amount received is less than the amount due.",
  },
  orderNumber: { ar: "رقم الطلب", en: "Order number" },
  invoiceNumber: { ar: "رقم الشيك", en: "Check number" },
  preparingCheck: { ar: "جاري تجهيز الشيك…", en: "Preparing check…" },
  verifyingPayment: {
    ar: "جاري التحقق من الدفع…",
    en: "Verifying payment…",
  },
  recoveryIncomplete: {
    ar: "تم تسجيل الدفع. تعذر تحميل الفاتورة للطباعة. لا تعِد المحاولة كدفعة جديدة.",
    en: "Payment is recorded. The receipt could not be loaded. Do not retry as a new payment.",
  },
  recoveryUnknown: {
    ar: "تعذر تأكيد نتيجة الدفع. لا تعِد المحاولة كدفعة جديدة قبل التحقق.",
    en: "Payment result could not be confirmed. Do not retry as a new payment until verified.",
  },
  recoveryInvalidTerminal: {
    ar: "الدفع غير مكتمل. لا يمكن اعتباره دفعًا ناجحًا.",
    en: "Payment is not complete. It cannot be treated as a successful payment.",
  },
  recoveryNotCommitted: {
    ar: "لم يُسجَّل الدفع. يمكنك المحاولة مرة أخرى.",
    en: "Payment was not recorded. You may try again.",
  },
  showActiveOrders: { ar: "الطلبات النشطة", en: "Active orders" },
  hideActiveOrders: { ar: "إخفاء الطلبات النشطة", en: "Hide active orders" },
  awaitingCashier: { ar: "بانتظار الكاشير", en: "Awaiting cashier" },
  incomingOrders: { ar: "طلبات واردة", en: "Incoming orders" },
  noIncomingOrders: {
    ar: "لا توجد طلبات بانتظار الدفع.",
    en: "No orders awaiting payment.",
  },
  incomingOrderItems: { ar: "صنف", en: "items" },
  cancelPayment: { ar: "إلغاء", en: "Cancel" },
  totalTendered: { ar: "إجمالي المدفوع", en: "Total tendered" },
  remainingAmount: { ar: "الباقي", en: "Remaining" },
  underpayment: {
    ar: "لا يمكن إتمام الدفع والمبلغ المتبقي أكبر من صفر.",
    en: "Payment cannot complete while an amount remains due.",
  },
  cardOverTender: {
    ar: "مبلغ البطاقة يجب أن يساوي المستحق أو يُكمَّل نقدًا حتى المستحق.",
    en: "Card must equal the amount due, or cash plus card must equal the amount due.",
  },
};

export function cashierUiLabel(key: keyof typeof COPY, language: CashierLang): string {
  return COPY[key][language];
}
