export {
  MINEUQR_CONNECTOR_MIN_DASHBOARD_VERSION as MINEUQR_CONNECTOR_MIN_CLOUD_VERSION,
  MINEUQR_CONNECTOR_PRODUCT_NAME,
  MINEUQR_CONNECTOR_VERSION,
  getWindowsInstallerFileName,
} from "./release/connectorRelease";
